-- ReChair OMS v0.8.5
-- Secure electronic rental contracts for personal and commercial rentals.
-- Run after v083_rental_retrieval_inventory.sql.

create extension if not exists pgcrypto;

create table if not exists public.rental_contracts (
  id uuid primary key default gen_random_uuid(),
  consultation_id uuid not null references public.consultations(id) on delete cascade,
  version integer not null default 1 check (version > 0),
  contract_no text not null unique,
  contract_type text not null check (contract_type in ('personal','commercial')),
  status text not null default 'draft'
    check (status in ('draft','sent','signed','superseded','void')),
  document_snapshot jsonb not null default '{}'::jsonb,
  document_sha256 text not null,
  terms_version text not null default '2026-08-v1',
  access_token_hash text unique,
  access_expires_at timestamptz,
  phone_verification_failures integer not null default 0 check (phone_verification_failures >= 0),
  phone_locked_until timestamptz,
  phone_verified_at timestamptz,
  signature_path text,
  signer_name text,
  contract_consent boolean not null default false,
  privacy_consent boolean not null default false,
  sent_at timestamptz,
  signed_at timestamptz,
  superseded_at timestamptz,
  voided_at timestamptz,
  void_reason text,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now(),
  unique (consultation_id, version)
);

create table if not exists public.rental_contract_events (
  id bigint generated by default as identity primary key,
  contract_id uuid not null references public.rental_contracts(id) on delete cascade,
  consultation_id uuid not null references public.consultations(id) on delete cascade,
  event_type text not null,
  actor_type text not null check (actor_type in ('admin','customer','system')),
  detail jsonb not null default '{}'::jsonb,
  created_at timestamptz not null default now()
);

alter table public.consultations
  add column if not exists rental_contract_id uuid references public.rental_contracts(id);

alter table public.consultations
  add column if not exists rental_contract_version integer;

alter table public.consultations
  add column if not exists rental_contract_document_hash text;

create index if not exists rental_contracts_consultation_created_idx
  on public.rental_contracts(consultation_id, created_at desc);

create index if not exists rental_contracts_status_idx
  on public.rental_contracts(status, updated_at desc);

create unique index if not exists rental_contracts_one_open_draft_idx
  on public.rental_contracts(consultation_id)
  where status in ('draft','sent');

create index if not exists rental_contract_events_contract_idx
  on public.rental_contract_events(contract_id, created_at);

alter table public.rental_contracts enable row level security;
alter table public.rental_contract_events enable row level security;
revoke all on table public.rental_contracts from anon, authenticated;
revoke all on table public.rental_contract_events from anon, authenticated;

insert into storage.buckets (id, name, public)
values ('rental-contract-signatures', 'rental-contract-signatures', false)
on conflict (id) do update set public = false;

drop policy if exists "public read rental contract signatures" on storage.objects;
drop policy if exists "public upload rental contract signatures" on storage.objects;
drop policy if exists "anon read rental contract signatures" on storage.objects;
drop policy if exists "anon upload rental contract signatures" on storage.objects;

-- Signed documents are immutable. Only access-link fields and superseding metadata
-- may change after signing so the original contract snapshot remains evidence.
create or replace function public.protect_signed_rental_contract()
returns trigger
language plpgsql
as $$
begin
  if old.status in ('signed','superseded') then
    if new.consultation_id is distinct from old.consultation_id
      or new.version is distinct from old.version
      or new.contract_no is distinct from old.contract_no
      or new.contract_type is distinct from old.contract_type
      or new.document_snapshot is distinct from old.document_snapshot
      or new.document_sha256 is distinct from old.document_sha256
      or new.terms_version is distinct from old.terms_version
      or new.signature_path is distinct from old.signature_path
      or new.signer_name is distinct from old.signer_name
      or new.contract_consent is distinct from old.contract_consent
      or new.privacy_consent is distinct from old.privacy_consent
      or new.signed_at is distinct from old.signed_at then
      raise exception 'SIGNED_RENTAL_CONTRACT_IMMUTABLE';
    end if;
  end if;
  return new;
end;
$$;

drop trigger if exists rental_contracts_protect_signed on public.rental_contracts;
create trigger rental_contracts_protect_signed
before update on public.rental_contracts
for each row execute function public.protect_signed_rental_contract();

-- Completes signing and updates the existing nine-stage rental workflow in one
-- database transaction. Only server-side service-role APIs can execute it.
create or replace function public.complete_rental_contract(
  p_contract_id uuid,
  p_signature_path text,
  p_signer_name text,
  p_signed_at timestamptz default now()
)
returns public.rental_contracts
language plpgsql
security definer
set search_path = public
as $$
declare
  current_contract public.rental_contracts%rowtype;
  completed_contract public.rental_contracts%rowtype;
  retention_until timestamptz;
  contract_end_date date;
begin
  select * into current_contract
  from public.rental_contracts
  where id = p_contract_id
  for update;

  if current_contract.id is null then
    raise exception 'RENTAL_CONTRACT_NOT_FOUND';
  end if;
  if current_contract.status <> 'sent' then
    raise exception 'RENTAL_CONTRACT_NOT_SIGNABLE';
  end if;
  if current_contract.access_expires_at is not null
     and current_contract.access_expires_at < p_signed_at then
    raise exception 'RENTAL_CONTRACT_LINK_EXPIRED';
  end if;
  if current_contract.phone_verified_at is null then
    raise exception 'RENTAL_CONTRACT_PHONE_NOT_VERIFIED';
  end if;

  update public.rental_contracts
  set status = 'superseded',
      superseded_at = p_signed_at,
      updated_at = p_signed_at
  where consultation_id = current_contract.consultation_id
    and id <> current_contract.id
    and status = 'signed';

  update public.rental_contracts
  set status = 'signed',
      signature_path = p_signature_path,
      signer_name = p_signer_name,
      contract_consent = true,
      privacy_consent = true,
      signed_at = p_signed_at,
      updated_at = p_signed_at
  where id = current_contract.id
  returning * into completed_contract;

  if coalesce(completed_contract.document_snapshot #>> '{period,end_date}', '')
     ~ '^[0-9]{4}-[0-9]{2}-[0-9]{2}$' then
    contract_end_date := (completed_contract.document_snapshot #>> '{period,end_date}')::date;
  end if;

  retention_until := greatest(
    p_signed_at + interval '5 years',
    coalesce(contract_end_date::timestamptz + interval '5 years', p_signed_at + interval '5 years')
  );

  update public.consultations
  set rental_contract_id = completed_contract.id,
      rental_contract_version = completed_contract.version,
      rental_contract_document_hash = completed_contract.document_sha256,
      rental_contract_no = completed_contract.contract_no,
      rental_contract_signed_at = completed_contract.signed_at,
      rental_stage = '계약완료',
      rental_stage_updated_at = p_signed_at,
      status = '계약완료',
      retention_expires_at = greatest(
        coalesce(retention_expires_at, retention_until),
        retention_until
      ),
      updated_at = p_signed_at
  where id = completed_contract.consultation_id;

  insert into public.rental_contract_events(
    contract_id, consultation_id, event_type, actor_type, detail
  ) values (
    completed_contract.id,
    completed_contract.consultation_id,
    'signed',
    'customer',
    jsonb_build_object(
      'version', completed_contract.version,
      'document_sha256', completed_contract.document_sha256
    )
  );

  return completed_contract;
end;
$$;

revoke all on function public.complete_rental_contract(uuid,text,text,timestamptz)
  from public, anon, authenticated;
grant execute on function public.complete_rental_contract(uuid,text,text,timestamptz)
  to service_role;
