-- ReChair OMS v0.8.7
-- Serial-level rental asset registry and lifecycle linkage.
-- Run after supabase/v086_rental_contract_party_types.sql.

create extension if not exists pgcrypto;

alter table public.products
  add column if not exists rental_asset_managed boolean not null default false;

create table if not exists public.rental_assets (
  id uuid primary key default gen_random_uuid(),
  asset_no text not null unique,
  product_id uuid references public.products(id) on delete set null,
  serial_number text,
  title text not null,
  brand text,
  model_name text,
  rental_type text check (rental_type is null or rental_type in ('personal','commercial')),
  status text not null default '렌탈가능'
    check (status in (
      '렌탈가능','배정완료','설치예약','렌탈중','회수예정',
      '점검중','정비중','폐기검토','폐기완료'
    )),
  condition_grade text not null default 'A급',
  location_type text not null default '창고'
    check (location_type in ('창고','고객설치','기사보관','정비처','폐기','기타')),
  location_text text,
  current_consultation_id uuid references public.consultations(id) on delete set null,
  acquired_at date,
  acquisition_cost numeric not null default 0 check (acquisition_cost >= 0),
  installed_at timestamptz,
  returned_at timestamptz,
  memo text,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);

create table if not exists public.rental_asset_events (
  id bigint generated by default as identity primary key,
  asset_id uuid not null references public.rental_assets(id) on delete cascade,
  consultation_id uuid references public.consultations(id) on delete set null,
  schedule_id uuid references public.service_schedules(id) on delete set null,
  event_type text not null,
  from_status text,
  to_status text,
  actor_type text not null default 'admin'
    check (actor_type in ('admin','technician','system')),
  detail jsonb not null default '{}'::jsonb,
  created_at timestamptz not null default now()
);

alter table public.consultations
  add column if not exists rental_asset_id uuid references public.rental_assets(id) on delete set null;

alter table public.service_schedules
  add column if not exists rental_asset_id uuid references public.rental_assets(id) on delete set null;

create unique index if not exists rental_assets_serial_number_unique_idx
  on public.rental_assets(lower(serial_number))
  where nullif(trim(serial_number),'') is not null;

create unique index if not exists rental_assets_current_consultation_unique_idx
  on public.rental_assets(current_consultation_id)
  where current_consultation_id is not null;

create index if not exists rental_assets_product_status_idx
  on public.rental_assets(product_id,status);

create index if not exists rental_assets_status_updated_idx
  on public.rental_assets(status,updated_at desc);

create index if not exists rental_asset_events_asset_created_idx
  on public.rental_asset_events(asset_id,created_at desc);

create index if not exists consultations_rental_asset_idx
  on public.consultations(rental_asset_id)
  where rental_asset_id is not null;

create index if not exists service_schedules_rental_asset_idx
  on public.service_schedules(rental_asset_id)
  where rental_asset_id is not null;

alter table public.rental_assets enable row level security;
alter table public.rental_asset_events enable row level security;
revoke all on table public.rental_assets from anon, authenticated;
revoke all on table public.rental_asset_events from anon, authenticated;

-- Assigning and releasing an asset touches both the consultation and physical
-- asset. These functions keep both rows consistent in one transaction.
create or replace function public.assign_rental_asset(
  p_consultation_id uuid,
  p_asset_id uuid
)
returns public.rental_assets
language plpgsql
security definer
set search_path = public
as $$
declare
  target_consultation public.consultations%rowtype;
  target_asset public.rental_assets%rowtype;
  previous_asset public.rental_assets%rowtype;
  assigned_status text;
begin
  select * into target_consultation
  from public.consultations
  where id = p_consultation_id
  for update;

  if target_consultation.id is null then
    raise exception 'RENTAL_CONSULTATION_NOT_FOUND';
  end if;
  if position('렌탈' in coalesce(target_consultation.service_type,'')) = 0 then
    raise exception 'NOT_RENTAL_CONSULTATION';
  end if;
  if target_consultation.rental_contract_signed_at is null
     and coalesce(target_consultation.rental_stage,'') <> '운영중' then
    raise exception 'SIGNED_RENTAL_CONTRACT_REQUIRED';
  end if;
  if coalesce(target_consultation.rental_stage,'') not in ('계약완료','설치예약','운영중') then
    raise exception 'RENTAL_ASSET_ASSIGNMENT_STAGE';
  end if;
  assigned_status := case
    when target_consultation.rental_stage = '운영중' then '렌탈중'
    else '배정완료'
  end;

  if target_consultation.rental_asset_id = p_asset_id then
    select * into target_asset from public.rental_assets where id = p_asset_id;
    return target_asset;
  end if;

  if target_consultation.rental_asset_id is not null then
    select * into previous_asset
    from public.rental_assets
    where id = target_consultation.rental_asset_id
    for update;

    if previous_asset.id is not null then
      if previous_asset.status <> '배정완료' then
        raise exception 'PREVIOUS_RENTAL_ASSET_LOCKED';
      end if;
      update public.rental_assets
      set status = '렌탈가능',
          current_consultation_id = null,
          updated_at = now()
      where id = previous_asset.id;

      insert into public.rental_asset_events(
        asset_id,consultation_id,event_type,from_status,to_status,actor_type,detail
      ) values (
        previous_asset.id,p_consultation_id,'assignment_replaced',
        previous_asset.status,'렌탈가능','admin',jsonb_build_object('next_asset_id',p_asset_id)
      );
    end if;
  end if;

  select * into target_asset
  from public.rental_assets
  where id = p_asset_id
  for update;

  if target_asset.id is null then
    raise exception 'RENTAL_ASSET_NOT_FOUND';
  end if;
  if target_asset.status <> '렌탈가능' or target_asset.current_consultation_id is not null then
    raise exception 'RENTAL_ASSET_NOT_AVAILABLE';
  end if;
  if target_consultation.product_id is null or target_asset.product_id is distinct from target_consultation.product_id then
    raise exception 'RENTAL_ASSET_PRODUCT_MISMATCH';
  end if;

  update public.rental_assets
  set status = assigned_status,
      current_consultation_id = p_consultation_id,
      location_type = case when assigned_status = '렌탈중' then '고객설치' else '창고' end,
      location_text = case when assigned_status = '렌탈중' then target_consultation.address else location_text end,
      installed_at = case
        when assigned_status = '렌탈중' then coalesce(
          target_consultation.rental_installation_completed_at,
          target_consultation.rental_operating_started_at,
          now()
        )
        else installed_at
      end,
      returned_at = null,
      updated_at = now()
  where id = target_asset.id
  returning * into target_asset;

  update public.consultations
  set rental_asset_id = target_asset.id,
      updated_at = now()
  where id = p_consultation_id;

  insert into public.rental_asset_events(
    asset_id,consultation_id,event_type,from_status,to_status,actor_type,detail
  ) values (
    target_asset.id,p_consultation_id,'assigned',
    '렌탈가능',assigned_status,'admin',jsonb_build_object(
      'rental_stage',target_consultation.rental_stage,
      'existing_operation_migration',target_consultation.rental_stage = '운영중'
    )
  );

  return target_asset;
end;
$$;

create or replace function public.release_rental_asset(
  p_consultation_id uuid
)
returns public.rental_assets
language plpgsql
security definer
set search_path = public
as $$
declare
  target_consultation public.consultations%rowtype;
  target_asset public.rental_assets%rowtype;
begin
  select * into target_consultation
  from public.consultations
  where id = p_consultation_id
  for update;

  if target_consultation.id is null or target_consultation.rental_asset_id is null then
    raise exception 'RENTAL_ASSET_ASSIGNMENT_NOT_FOUND';
  end if;

  select * into target_asset
  from public.rental_assets
  where id = target_consultation.rental_asset_id
  for update;

  if target_asset.id is null then
    raise exception 'RENTAL_ASSET_NOT_FOUND';
  end if;
  if target_asset.status <> '배정완료' then
    raise exception 'RENTAL_ASSET_RELEASE_LOCKED';
  end if;
  if exists (
    select 1 from public.service_schedules
    where consultation_id = p_consultation_id
      and schedule_kind = 'rental_installation'
      and status <> '취소'
  ) then
    raise exception 'RENTAL_INSTALLATION_ALREADY_CREATED';
  end if;

  update public.rental_assets
  set status = '렌탈가능',
      current_consultation_id = null,
      updated_at = now()
  where id = target_asset.id
  returning * into target_asset;

  update public.consultations
  set rental_asset_id = null,
      updated_at = now()
  where id = p_consultation_id;

  insert into public.rental_asset_events(
    asset_id,consultation_id,event_type,from_status,to_status,actor_type,detail
  ) values (
    target_asset.id,p_consultation_id,'assignment_released',
    '배정완료','렌탈가능','admin','{}'::jsonb
  );

  return target_asset;
end;
$$;

revoke all on function public.assign_rental_asset(uuid,uuid) from public,anon,authenticated;
revoke all on function public.release_rental_asset(uuid) from public,anon,authenticated;
grant execute on function public.assign_rental_asset(uuid,uuid) to service_role;
grant execute on function public.release_rental_asset(uuid) to service_role;
