from __future__ import annotations

from PySide6.QtCore import Qt
from PySide6.QtWidgets import (
    QGridLayout, QGroupBox, QLabel, QMainWindow, QPushButton, QProgressBar,
    QPlainTextEdit, QVBoxLayout, QWidget,
)


class UiMainWindow:
    def setup_ui(self, window: QMainWindow) -> None:
        window.setWindowTitle("CPMS Enterprise 1.0 Beta 4")
        window.resize(820, 620)

        root = QWidget()
        layout = QVBoxLayout(root)
        layout.setContentsMargins(18, 18, 18, 18)
        layout.setSpacing(12)

        title = QLabel("CPMS ENTERPRISE 1.0 BETA 4")
        title.setAlignment(Qt.AlignCenter)
        title.setStyleSheet("font-size: 25px; font-weight: 700;")
        layout.addWidget(title)

        master_box = QGroupBox("제조사 Master 상태")
        master_layout = QGridLayout(master_box)
        self.master_label = QLabel("Manufacturers/IR·XC·AC·KA·NC/Master/Master.xlsx")
        self.update_count_label = QLabel("Update 대기: 0건")
        self.manufacturer_status_label = QLabel("IR: - / XC: - / AC: - / KA: - / NC: -")
        self.ocr_status_label = QLabel("확인 중")
        self.safety_status_label = QLabel("미실행")
        master_layout.addWidget(QLabel("Master"), 0, 0)
        master_layout.addWidget(self.master_label, 0, 1)
        master_layout.addWidget(QLabel("대기"), 1, 0)
        master_layout.addWidget(self.update_count_label, 1, 1)
        master_layout.addWidget(QLabel("상태"), 2, 0)
        master_layout.addWidget(self.manufacturer_status_label, 2, 1)
        master_layout.addWidget(QLabel("OCR"), 3, 0)
        master_layout.addWidget(self.ocr_status_label, 3, 1)
        master_layout.addWidget(QLabel("안전"), 4, 0)
        master_layout.addWidget(self.safety_status_label, 4, 1)
        layout.addWidget(master_box)

        result_box = QGroupBox("결과")
        result_layout = QGridLayout(result_box)
        self.new_parts_label = QLabel("0")
        self.kr_label = QLabel("0")
        self.price_label = QLabel("0")
        self.duplicate_label = QLabel("0")
        result_layout.addWidget(QLabel("신규부품"), 0, 0)
        result_layout.addWidget(self.new_parts_label, 0, 1)
        result_layout.addWidget(QLabel("KR보완"), 0, 2)
        result_layout.addWidget(self.kr_label, 0, 3)
        result_layout.addWidget(QLabel("이번 실행 가격이력 검출"), 1, 0)
        result_layout.addWidget(self.price_label, 1, 1)
        result_layout.addWidget(QLabel("중복"), 1, 2)
        result_layout.addWidget(self.duplicate_label, 1, 3)
        layout.addWidget(result_box)

        workflow_box = QGroupBox("업무 흐름 현황")
        workflow_layout = QGridLayout(workflow_box)
        self.workflow_pending_label = QLabel("0")
        self.workflow_review_label = QLabel("0")
        self.workflow_completed_label = QLabel("0")
        self.workflow_next_label = QLabel("문서 자동 분류")
        workflow_layout.addWidget(QLabel("Update 남음"), 0, 0)
        workflow_layout.addWidget(self.workflow_pending_label, 0, 1)
        workflow_layout.addWidget(QLabel("승인·검토 대기"), 0, 2)
        workflow_layout.addWidget(self.workflow_review_label, 0, 3)
        workflow_layout.addWidget(QLabel("최근 처리완료"), 1, 0)
        workflow_layout.addWidget(self.workflow_completed_label, 1, 1)
        workflow_layout.addWidget(QLabel("권장 다음 단계"), 1, 2)
        workflow_layout.addWidget(self.workflow_next_label, 1, 3)
        layout.addWidget(workflow_box)

        self.progressbar = QProgressBar(); self.progressbar.setRange(0, 100)
        layout.addWidget(self.progressbar)

        self.textbox = QPlainTextEdit(); self.textbox.setReadOnly(True)
        layout.addWidget(self.textbox, stretch=1)

        self.btn_simulate = QPushButton("업데이트 시뮬레이션")
        self.btn_update = QPushButton("업데이트 시작")
        self.btn_rebuild = QPushButton("전체 재생성")
        self.btn_search = QPushButton("History 조회")
        self.btn_log = QPushButton("로그 위치")
        self.btn_ocr = QPushButton("OCR 상태")
        self.btn_purchase = QPushButton("발주 분석")
        self.btn_pdf_review = QPushButton("PDF 검토/승인")
        self.btn_diagnostic = QPushButton("파일 진단")
        self.btn_multidoc = QPushButton("다중문서 안전 분석")
        self.btn_review_center = QPushButton("다중문서 승인센터")
        self.btn_route = QPushButton("문서 자동 분류")
        self.btn_workflow = QPushButton("업무 흐름 현황")
        self.btn_wizard = QPushButton("업무 흐름 마법사")
        self.btn_safety = QPushButton("안전 점검")
        button_layout = QGridLayout()
        button_layout.addWidget(self.btn_simulate, 0, 0)
        button_layout.addWidget(self.btn_update, 0, 1)
        button_layout.addWidget(self.btn_rebuild, 0, 2)
        button_layout.addWidget(self.btn_search, 0, 3)
        button_layout.addWidget(self.btn_log, 0, 4)
        button_layout.addWidget(self.btn_ocr, 1, 4)
        button_layout.addWidget(self.btn_purchase, 1, 0, 1, 3)
        button_layout.addWidget(self.btn_pdf_review, 1, 3)
        button_layout.addWidget(self.btn_diagnostic, 1, 4)
        button_layout.addWidget(self.btn_multidoc, 2, 0, 1, 3)
        button_layout.addWidget(self.btn_review_center, 2, 3, 1, 2)
        button_layout.addWidget(self.btn_route, 3, 0, 1, 3)
        button_layout.addWidget(self.btn_workflow, 3, 3, 1, 2)
        button_layout.addWidget(self.btn_wizard, 4, 0, 1, 5)
        button_layout.addWidget(self.btn_safety, 5, 0, 1, 5)
        layout.addLayout(button_layout)
        window.setCentralWidget(root)
