'use client';
import { FormEvent, useEffect, useState } from 'react';
const initial={title:'',brand:'',model_name:'',price:'',grade:'A급',status:'판매중',year_text:'',region:'',warranty_text:'',thumbnail_url:'',description:'',stock_qty:'1',is_visible:true,is_featured:false};
export default function AdminProducts(){const [products,setProducts]=useState<any[]>([]);const [form,setForm]=useState(initial);const [message,setMessage]=useState('');const load=async()=>{const r=await fetch('/api/products');const j=await r.json();if(r.ok)setProducts(j.data||[])};useEffect(()=>{load()},[]);
 const submit=async(e:FormEvent)=>{e.preventDefault();setMessage('등록 중...');const r=await fetch('/api/products',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({...form,price:Number(form.price||0),stock_qty:Number(form.stock_qty||1),photo_urls:form.thumbnail_url?[form.thumbnail_url]:[]})});const j=await r.json();if(!r.ok){setMessage(j.error||'등록 실패');return}setMessage('상품이 등록되었습니다.');setForm(initial);load()};
 const toggle=async(p:any)=>{await fetch(`/api/products/${p.id}`,{method:'PATCH',headers:{'Content-Type':'application/json'},body:JSON.stringify({is_visible:!p.is_visible})});load()};
 return <div className="rc-admin-products"><section className="rc-admin-product-form"><h1>상품 등록</h1><form onSubmit={submit}><div className="rc-admin-form-grid">
 {['title','brand','model_name','price','year_text','region','stock_qty','warranty_text','thumbnail_url'].map((k)=><label key={k} className={k==='thumbnail_url'?'rc-admin-full':''}><span>{{title:'상품명',brand:'브랜드',model_name:'모델명',price:'가격',year_text:'연식',region:'지역',stock_qty:'재고',warranty_text:'AS 안내',thumbnail_url:'대표 이미지 URL'}[k as keyof typeof initial] as string}</span><input value={(form as any)[k]} onChange={e=>setForm({...form,[k]:k==='price'||k==='stock_qty'?e.target.value.replace(/\D/g,''):e.target.value})}/></label>)}
 <label><span>등급</span><select value={form.grade} onChange={e=>setForm({...form,grade:e.target.value})}><option>A급</option><option>B급</option><option>리퍼</option></select></label><label><span>상태</span><select value={form.status} onChange={e=>setForm({...form,status:e.target.value})}><option>판매중</option><option>상담가능</option><option>예약중</option><option>판매완료</option></select></label>
 <label className="rc-admin-full"><span>설명</span><textarea rows={5} value={form.description} onChange={e=>setForm({...form,description:e.target.value})}/></label></div>
 <div className="rc-admin-checks"><label><input type="checkbox" checked={form.is_visible} onChange={e=>setForm({...form,is_visible:e.target.checked})}/> 홈페이지 노출</label><label><input type="checkbox" checked={form.is_featured} onChange={e=>setForm({...form,is_featured:e.target.checked})}/> 추천상품</label></div><button type="submit">상품 등록</button>{message&&<p>{message}</p>}</form></section>
 <section className="rc-admin-product-list"><h2>등록 상품</h2>{products.map(p=><div className="rc-admin-product-row" key={p.id}><div><strong>{p.title}</strong><small>{p.brand} · {p.model_name}</small></div><span>{Number(p.price).toLocaleString('ko-KR')}원</span><span>{p.status}</span><button onClick={()=>toggle(p)}>{p.is_visible?'노출중':'숨김'}</button></div>)}</section></div>}
