'use client';
import { useEffect, useState } from 'react';
type Consultation={id:string;name:string;phone:string;service_type:string;model:string;message:string;status:string;assignee?:string;memo?:string;quote_amount?:number;created_at:string;front_photo?:string;side_photo?:string;label_photo?:string;back_photo?:string;extra_photo?:string};
const labels:any={front_photo:'앞면',side_photo:'옆면',label_photo:'제품라벨',back_photo:'뒷면',extra_photo:'추가'};
export default function AdminConsultations(){
 const [items,setItems]=useState<Consultation[]>([]); const [selected,setSelected]=useState<Consultation|null>(null); const [loading,setLoading]=useState(false);
 async function load(){setLoading(true); const r=await fetch('/api/consultations',{cache:'no-store'}); const j=await r.json(); const arr=j.items||[]; setItems(arr); setSelected(arr[0]||null); setLoading(false)}
 useEffect(()=>{load()},[]);
 async function update(partial:any){ if(!selected?.id) return; const r=await fetch(`/api/consultations/${selected.id}`,{method:'PATCH',headers:{'Content-Type':'application/json'},body:JSON.stringify(partial)}); if(r.ok){const j=await r.json(); setSelected(j.item); setItems(prev=>prev.map(x=>x.id===j.item.id?j.item:x));}}
 const photos=['front_photo','side_photo','label_photo','back_photo','extra_photo'].filter(k=>(selected as any)?.[k]);
 return <div className="admin-grid"><div className="list"><div style={{display:'flex',justifyContent:'space-between',alignItems:'center'}}><h2>상담 접수 CRM</h2><button className="btn btn-dark" onClick={load}>{loading?'조회 중':'새로고침'}</button></div><p><b>{items.length}</b>건</p>{items.length===0&&<p style={{color:'#64748b'}}>접수된 상담이 없습니다.</p>}{items.map(item=><div key={item.id} className="list-item" onClick={()=>setSelected(item)}><b>{item.name}</b><span style={{float:'right',background:'#071024',color:'#fff',borderRadius:99,padding:'4px 10px',fontSize:12}}>{item.status||'신규'}</span><p>{item.service_type}</p><b>{item.model}</b></div>)}</div><div className="detail">{selected?<><p style={{color:'#2769ff',fontWeight:900}}>{selected.service_type}</p><h1>{selected.name}</h1><p>{selected.phone}</p><select className="select" value={selected.status||'신규'} onChange={e=>update({status:e.target.value})}><option>신규</option><option>상담중</option><option>견적발송</option><option>예약완료</option><option>방문완료</option><option>판매완료</option><option>종료</option></select><div className="grid2"><div className="detail-card"><p>브랜드/모델</p><h2>{selected.model||'-'}</h2></div><div className="detail-card"><p>접수일</p><h2>{selected.created_at?new Date(selected.created_at).toLocaleString('ko-KR'):'-'}</h2></div></div><div className="detail-card"><p>문의 내용</p><p>{selected.message||'-'}</p></div><h2>첨부 사진</h2>{photos.length?<div className="photo-view">{photos.map(k=><a key={k} href={(selected as any)[k]} target="_blank"><img src={(selected as any)[k]} alt={labels[k]}/><p style={{textAlign:'center',fontWeight:900}}>{labels[k]}</p></a>)}</div>:<p style={{color:'#64748b'}}>첨부 사진이 없습니다.</p>}<div className="grid2" style={{marginTop:20}}><input className="input" placeholder="담당자" defaultValue={selected.assignee||''} onBlur={e=>update({assignee:e.target.value})}/><input className="input" type="number" placeholder="견적금액" defaultValue={selected.quote_amount||''} onBlur={e=>update({quote_amount:Number(e.target.value||0)})}/></div><textarea className="textarea" placeholder="관리자 메모" defaultValue={selected.memo||''} onBlur={e=>update({memo:e.target.value})} style={{marginTop:14}}/></>:<p>상담을 선택하세요.</p>}</div></div>
}
