'use client';
import { useState } from 'react';
const photoInputs=[['front_photo','앞면 사진','제품 전체 정면이 보이게 촬영'],['side_photo','옆면 사진','팔걸이/측면 외관이 보이게 촬영'],['label_photo','모델명/제품라벨','제품 뒤 또는 하단 라벨을 선명하게 촬영'],['back_photo','뒷면 사진','후면 커버와 전원부가 보이게 촬영']];
export default function ConsultationForm(){
 const [previews,setPreviews]=useState<Record<string,string>>({}); const [loading,setLoading]=useState(false);
 function onFile(name:string,file?:File){ if(!file) return; setPreviews(p=>({...p,[name]:URL.createObjectURL(file)})); }
 async function submit(e:React.FormEvent<HTMLFormElement>){ e.preventDefault(); setLoading(true); const form=new FormData(e.currentTarget); const res=await fetch('/api/consultations',{method:'POST',body:form}); setLoading(false); if(res.ok){alert('상담이 접수되었습니다. 담당자가 연락드리겠습니다.'); e.currentTarget.reset(); setPreviews({});} else alert('접수 중 오류가 발생했습니다.'); }
 return <section id="quote" className="form-section"><div className="container"><div className="quote"><div><p style={{color:'#6ee7ff',fontWeight:900}}>Free Quote</p><h2>사진만 보내도 빠르게<br/>상담받을 수 있습니다.</h2><p>앞면, 옆면, 제품라벨, 뒷면 사진을 올려주시면 제품 상태를 더 정확히 확인할 수 있습니다.</p></div><form className="quote-form" onSubmit={submit}><div className="grid2"><input className="input" name="name" placeholder="이름" required/><input className="input" name="phone" placeholder="연락처" required/></div><select className="select" name="service_type" required style={{marginTop:14}}><option>중고 안마의자 구매</option><option>중고 안마의자 판매</option><option>이전설치</option><option>폐기수거</option><option>출장수리</option><option>부품문의</option></select><input className="input" name="model" placeholder="브랜드/모델명 예: 코지마 CMC-A100" style={{marginTop:14}}/><textarea className="textarea" name="message" placeholder="문의 내용을 적어주세요" style={{marginTop:14}}/><div style={{marginTop:18,fontWeight:900}}>제품 상태 사진 첨부</div><p style={{color:'#64748b',fontSize:14}}>사진을 많이 올릴수록 더 빠르고 정확한 상담이 가능합니다.</p><div className="photo-grid">{photoInputs.map(([name,label,desc])=><div className="photo-box" key={name}><label>{label}</label>{previews[name]?<img className="preview" src={previews[name]} alt={label}/>:<div className="preview">📷 예시</div>}<input type="file" name={name} accept="image/*" capture="environment" onChange={e=>onFile(name,e.target.files?.[0])}/><p style={{fontSize:12,color:'#64748b'}}>{desc}</p></div>)}</div><button className="btn" style={{width:'100%',fontSize:18}} disabled={loading}>{loading?'접수 중...':'무료 상담 신청'}</button></form></div></div></section>
}
